spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/postgres
#    url: jdbc:postgresql://localhost:5432/postgres

#    DATABASE_PUBLIC_URL
#    url: jdbc:postgresql://turntable.proxy.rlwy.net:15640/postgres
#    DATABASE_URL
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: dkKarLfDxDEQyoxFQrXXhbfnHmAfsUDm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true


testing:
  app:
    secret: ljb3w443eifubw23
    expirationMs: 60000